import { describe, expect, it } from "vitest";
import { parseMbPubKey, formatMbPubKey } from "../src/multiformat.js";
import { publicKeyBytesFromJwk, publicKeyJwkParams } from "../src/sign.js";
import vectors from "./fixtures/jwk-vectors.json" with { type: "json" };

/**
 * JWK <-> MBPubKey round-trip vectors published by the reference
 * implementation's author in
 * https://github.com/LedgerDomain/did-webplus/issues/36#issuecomment-4921395845
 * (generated by `test_roundtrip_public_key_params` in did-webplus-core).
 * Ed448 / P-384 / P-521 vectors from that comment are excluded: those curves
 * are not supported here yet.
 */
describe("reference JWK round-trip vectors", () => {
  it.each(vectors.map((v) => [v.crv, v] as const))(
    "MBPubKey -> JWK matches (%s %#)",
    (_crv, vector) => {
      const { curve, keyBytes } = parseMbPubKey(vector.mbPubKey);
      const jwk = publicKeyJwkParams(keyBytes, curve);
      expect(jwk.crv).toBe(vector.crv);
      expect(jwk.x).toBe(vector.x);
      if ("y" in vector) {
        expect(jwk.y).toBe(vector.y);
      } else {
        expect(jwk.y).toBeUndefined();
      }
    },
  );

  it.each(vectors.map((v) => [v.crv, v] as const))(
    "JWK -> MBPubKey matches (%s %#)",
    (_crv, vector) => {
      const { curve, publicKey } = publicKeyBytesFromJwk(vector);
      expect(formatMbPubKey(publicKey, curve)).toBe(vector.mbPubKey);
    },
  );
});