import { describe, expect, it } from "vitest";
import { formatMbPubKey, parseMbPubKey, type CurveName } from "../src/multiformat.js";

/**
 * MBPubKey test vectors published by the reference implementation's author in
 * https://github.com/LedgerDomain/did-webplus/issues/36#issuecomment-4912593264
 * (generated by the `test_generate_some_mb_pub_keys` test in LedgerDomain/mbx).
 * Base64Url representations, the form used in DID documents.
 */
const VECTORS: Array<[CurveName, string, number]> = [
  ["ed25519", "u7QGtAsLHvmbJgSO-kWM8jfldMVlfqIVwfZ2iUiylu8N-Aw", 32],
  ["secp256k1", "u5wECTDniPlnaegpcYBqwE6o8B4iVhtyYm168Z21Iy9wPMTs", 33],
  ["p256", "ugCQDdriKWDuuawhm5RnVSQHOPN7YW7NRP0bVSUf-3_vh3l8", 33],
];

describe("mbx MBPubKey reference vectors", () => {
  it.each(VECTORS)("parses and round-trips the %s vector", (curve, vector, keyLength) => {
    const parsed = parseMbPubKey(vector);
    expect(parsed.curve).toBe(curve);
    expect(parsed.keyBytes).toHaveLength(keyLength);
    expect(formatMbPubKey(parsed.keyBytes, parsed.curve)).toBe(vector);
  });
});
